### ISSUE TITLE
Search - Issue with Android

### ISSUE THREAD

**Issue by 0xFF0** [theQRL/block-explorer#272] opened 2019-01-21 02:05 UTC
**Action**: On Android with chrome, navigate to https://explorer.theqrl.org/search. Try to touch the search inputbox.
**What happened**: It's very difficult to search and/or paste something on the mobile site. You need to touch where the arrow is to have the keyboard and/or paste some text. If you touch the inputbox, it's the text below that is selected (i.e: The Quantum Resistant Ledger).
**Android/iOS version**: 7.1.2
**Android/iOS handset model**: NoxPlayer 6.2.6.1 (Samsung S8 emulation).

![search](https://user-images.githubusercontent.com/42574567/51447491-c84f2380-1cec-11e9-8d33-ebd795299503.png)

**Comment by jplomas** [comment] 2019-02-09 18:49
The footer had padding/margin which overlapped the input bar.  It was possible to select the box on mobile, but having now located the cause this is an easy fix.  It has been deployed in Devnet and will be merged through into Testnet and Mainnet shortly.

Thanks for the bug report.

**Comment by jplomas** [comment] 2019-02-10 08:07
Fixed in #275

**Closed by jplomas** 2019-02-10 08:07 UTC
Labels: Priority: Medium, Status: In Progress, Type: Bug
